name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # ou a versão que você está utilizando

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test  # substitua pelo comando correto para rodar seus testes

  build:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # ou a versão que você está utilizando

      - name: Build project
        run: npm run build  # substitua pelo comando correto para build

  versioning:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # ou a versão que você está utilizando

      - name: Versioning
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm version patch  # ou major/minor, conforme sua necessidade
          git push origin master --tags
